version: '3.1'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      AWS_DEFAULT_REGION: ap-esat-1
      AWS_ACCESS_KEY_ID: teste123
      AWS_SECRET_ACCESS_KEY: teste123
      EDGE_PORT: 4566
      SERVICES: s3
      DEBUG: 1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    depends_on:
      - localstack
    build:
      context: ./app/
    container_name: app
    links:
      - localstack
    restart: always
    environment:
      AWS_DEFAULT_REGION: ap-esat-1
      AWS_ACCESS_KEY_ID: teste123
      AWS_SECRET_ACCESS_KEY: teste123
      BUCKET_NAME: bucket-teste
      AWS_URL: http://localstack:4566
    ports:
      - 5000:5000
    volumes:
      - ${TEMPDIR:-/tmp/app/uploads}:/app/uploads
      - ${TEMPDIR:-/tmp/app/downloads}:/app/downloads
